---
- name: Configure logind.conf
  become: yes
  template:
    src: logind.conf.j2
    dest: /etc/systemd/logind.conf
    owner: root
    group: root
    mode: 0644
  vars:
    item: "{{ logind }}"
  register: logind_conf

- name: Restart the systemd-logind
  become: yes
  systemd:
    name: systemd-logind
    state: restarted
  when: logind_conf.changed
