---
- name: Configure logind.conf
  become: yes
  template:
    src: logind.conf.j2
    dest: /etc/systemd/logind.conf
    owner: root
    group: root
    mode: 0644
  vars:
    item: "{{ logind }}"
  notify: restart systemd-logind
